### ISSUE TITLE
bad magic number in 'six'

### ISSUE THREAD

**Issue by chrisdamato** [benjaminp/six#359]
Fedora 33. Any dnf or yum command produces the same error message before the normal output of the command:

`Failed loading plugin "changelog": bad magic number in 'six': b'\x03\xf3\r\n'`

For example:

```
$ dnf info python3-six
Failed loading plugin "changelog": bad magic number in 'six': b'\x03\xf3\r\n'
Last metadata expiration check: 1:22:05 ago on Fri 01 Oct 2021 07:59:45 AM EDT.
Installed Packages
Name         : python3-six
Version      : 1.15.0
Release      : 2.fc33
Architecture : noarch
Size         : 104 k
Source       : python-six-1.15.0-2.fc33.src.rpm
Repository   : @System
From repo    : fedora
Summary      : Python 2 and 3 compatibility utilities
URL          : https://pypi.python.org/pypi/six
License      : MIT
Description  : python-six provides simple utilities for wrapping over differences between
             : Python 2 and Python 3.
             : Python 3 version.

```

I tried updating the system, reinstalling six using pip and dnf, no change.

If I start python3 and import six, there is no error message. If I disable the changelog plugin to dnf (a builtin apparently) the message does not appear.

Hope I'm doing this right. Thanks for any help you are able to provide.

**Comment by atc0005** [comment]
@chrisdamato I ran into this today. The culprit ended up being a `/usr/bin/six.pyc` file. This seems to have been created by the VMware Perl SDK installation process. Go figure.

Once I removed that file, the error went away.

**Comment by hroncok** [comment]
When you run e.g. `dnf` or any other commend that is written in Python and installed in `/usr/bin`, Python adds `/usr/bin` as `sys.path[0]`. When a file called `six.pyc` exists in there, it is imported instead of six and the import fails.

We (Fedora) would like to start using a flag in shebang lines of Python scripts installed in `/usr/bin` that would prevent this undesired behavior, but such flag does not exist yet (`-I` does that, but it also does other things). I've asked for such flag many winters ago in https://discuss.python.org/t/python-flag-envvar-not-to-put-current-directory-to-sys-path-but-dont-ignore-pythonpath/4235

**Comment by hroncok** [comment]
I've opened https://github.com/rpm-software-management/dnf/pull/1815 for dnf specifically, but this can happen to any Python script residing in a directory like `/usr/bin`.

**Comment by hroncok** [comment]
I've also opened https://discuss.python.org/t/should-console-scripts-entry-points-exclude-teh-scripts-directory-from-sys-path/13896 for console_scripts entry points (which dnf is not): https://discuss.python.org/t/should-console-scripts-entry-points-exclude-teh-scripts-directory-from-sys-path/13896
